# define networks
networks:
  re_network:
    driver: bridge

# define our services
#
# custom services
#   frontend: reactjs, vite (npm)
#   backend: fastapi
#
# data services:
#   astro (airflow / postgresql / dbt )

services:
  astro:
    build:
      context: ./pipelines/
      dockerfile: Dockerfile
    volumes:
      - ./pipelines/dbt_project:/usr/local/airflow/dbt_project
      - ./pipelines:/usr/local/airflow/pipelines
#      - airflow_data:/var/lib/airflow/data/
    ports:
      - 8181:8181
    networks:
      - re_network

#  re_ui:
#    container_name: re_ui
#    env_file:
#      - ./frontend/.env
#    build:
#      context: ./frontend/
#      dockerfile: ./Dockerfile
#    volumes:
#      - type: bind
#        source: ./frontend
#        target: /app
#      - /app/node_modules
#    working_dir: /app
#    ports:
#      - 5174:5174
#    networks:
#      - re_network
#
#  re_api:
#    container_name: re_api
#    env_file:
#      - api/.env
#    build:
#      context: api/
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./api:/app
#    ports:
#      - 8000:8000
#    expose:
#      - 8000
#    depends_on:
#       - re_astro
#    networks:
#      - re_network
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@localhost:5631

  jupyter_notebook:
    container_name: jupyter_notebook
    build:
      context: ./jupyter/
      dockerfile: Dockerfile
    volumes:
      - ./jupyter:/home/jesse/work
    ports:
      - 8888:8888
    networks:
      - re_network

