version: '3.8'

# define our volumes
volumes:
  postgres_data:
  kestra-data:
    driver: local

# define our services
#
# custom services
#   frontend: reactjs, vite (npm)
#   backend: fastapi
#
# data services:
#   astro (airflow / postgresql / dbt )
services:
  astro:
    container_name: astro
    build:
      context: ./pipelines/
      dockerfile: Dockerfile
    volumes:
      - ./pipelines/dbt_project:/usr/local/airflow/dbt_project
      - ./pipelines:/usr/local/airflow/pipelines
    ports:
      - 8181:8181
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__WEBSERVER__PORT=8181
#  capstoneui:
#    container_name: capstoneui
#    env_file:
#      - ./frontend/.env
#    build:
#      context: ./frontend/
#      dockerfile: ./Dockerfile
#    volumes:
#      - type: bind
#        source: ./frontend
#        target: /app
#      - /app/node_modules
#    working_dir: /app
#    ports:
#      - 5174:5174

#  capstoneapi:
#    container_name: capstoneapi
#    env_file:
#      - api/.env
#    build:
#      context: api/
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./api:/app
#    ports:
#      - 8000:8000
#    expose:
#      - 8000
#    depends_on:
#       - bipostgres
##       - couchbase
##         condition: service_healthy
#  bipostgres:
#    container_name: bipostgres
#    build:
#      context: ./postgres/
#      dockerfile: ./Dockerfile
#    volumes:
#      - type: bind
#        source: ./postgres/init.sql
#        target: /docker-entrypoint-initdb.d/10-init.sql
#      - type: bind
#        source: ./postgres/setup-permissions.sql
#        target: /docker-entrypoint-initdb.d/20-setup-permissions.sql
#      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - 5432:5432
#    expose:
#      - 5432


##networks:



#  secrets:
#   db-password:
#     file: db/password.txt
