name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

on-run-start:
  - '{{ create_schema_if_not_exists(target.schema) }}'

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_database: pipelines

models:
  dbt_project:
    staging:
      +materialized: view
      stg_stock_returns:
        enabled: true
      stg_quarterly_stock_returns:
        enabled: true
      stg_gdp:
        enabled: true
    intermediate:
      +materialized: table
    marts:
      +materialized: table
      final_stock_gdp_data:
        enabled: true
seeds:
  dbt_project:
    raw_stock_data:
      enabled: true
      +column_types:
        "Date": date
        "Open": float
        "High": float
        "Low": float
        "Close": float
        "Adj Close": float
        "Volume": bigint
        "Ticker": varchar
        "Company Name": varchar
        "Industry": varchar
        "Sector": varchar
        "Market Cap": bigint
        "Total Revenue": bigint
        "Net Income": bigint

    raw_government_bailout_stimulus:
      enabled: true
      +column_types:
        "Year": varchar
        "Originating Crisis": varchar
        "Policy Date": varchar
        "Policy Title": varchar
        "Policy Description": varchar
        "Federal Policy Number": varchar
        "Attribution Link": varchar
        "President": varchar
        "Vice President": varchar
        "Govt Intervention": varchar



    raw_gdp:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_unemployment_rate:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_cpi:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_nonfarm_payrolls:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_job_openings:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_average_hourly_earnings:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_total_wages_and_salaries:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_employment_cost_index:
      enabled: true
      +column_types:
        date: date
        value: float
    raw_average_weekly_earnings:
      enabled: true
      +column_types:
        date: date
        value: float