postgres:
    port: "5631"
project:
    name: rosy_economix
skip_parse: false
verbosity: debug
webserver:
    port: "8181"

deployments:
  - name: dev
    astro_runtime_version: 5.0.0
    executor: LocalExecutor
    triggerer: true
    environment_variables:
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        value: postgresql+psycopg2://airflow:airflow@postgres:5631/airflow
      - key: AIRFLOW__CELERY__RESULT_BACKEND
        value: db+postgresql+psycopg2://airflow:airflow@postgres:5631/airflow
