name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

on-run-start:
  - '{{ create_schema_if_not_exists(target.schema) }}'

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_database: pipelines

models:
  dbt_project:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table

seeds:
  dbt_project:
    raw_stock_data:
      enabled: true
      +column_types:
        "Date": date
        "Open": float
        "High": float
        "Low": float
        "Close": float
        "Adj Close": float
        "Volume": bigint
        "Ticker": varchar
        "Company Name": varchar
        "Industry": varchar
        "Sector": varchar
        "Market Cap": bigint
        "Total Revenue": bigint
        "Net Income": bigint
    gdp:
      enabled: true
      +column_types:
        date: date
        value: float
    unemployment_rate:
      enabled: true
      +column_types:
        date: date
        value: float
    cpi:
      enabled: true
      +column_types:
        date: date
        value: float